### ISSUE TITLE
yarn storybook fails

### ISSUE THREAD

**Issue by sken** [modern-atomic-design/modern-atomic-design.github.io#1]
![image](https://user-images.githubusercontent.com/184684/168972767-f2ea0801-4a2e-4775-8f87-7f855d5086b5.png)

**Comment by Fuasmattn** [comment]
Which node version are you using?
Could you try it using node v16?

**Comment by sken** [comment]
Seems to work with node >= 14 
You could add this to your package.json

`"engines": {
    "node": ">=14.x"
  }`
